name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_LOGIN }}" --password-stdin
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Build image
        run: make build-docker
      - name: Publish image
        run: make publish-docker
